spring:
    application:
          name: Spring Boot Auditing
    datasource:
        url: jdbc:mysql://localhost:3306/audit?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: root
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        show_sql: true
        open-in-view: false
        factory-class: org.springframework.data.envers.repository.support.EnversRevisionRepositoryFactoryBean
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

debug: true
liquibase:
  change-log: classpath:/liquibase/db.changelog-master.xml
